service: little-birdy

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-south-1
  memorySize: 2048

plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi.handler
   events:
     - http: ANY /